// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/gadgettracermanager.proto

package gadgettracermanager

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Label struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Label) Reset()         { *m = Label{} }
func (m *Label) String() string { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()    {}
func (*Label) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf3c9184062973a1, []int{0}
}

func (m *Label) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Label.Unmarshal(m, b)
}
func (m *Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Label.Marshal(b, m, deterministic)
}
func (m *Label) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Label.Merge(m, src)
}
func (m *Label) XXX_Size() int {
	return xxx_messageInfo_Label.Size(m)
}
func (m *Label) XXX_DiscardUnknown() {
	xxx_messageInfo_Label.DiscardUnknown(m)
}

var xxx_messageInfo_Label proto.InternalMessageInfo

func (m *Label) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Label) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AddContainerResponse struct {
	Debug                string   `protobuf:"bytes,1,opt,name=debug,proto3" json:"debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContainerResponse) Reset()         { *m = AddContainerResponse{} }
func (m *AddContainerResponse) String() string { return proto.CompactTextString(m) }
func (*AddContainerResponse) ProtoMessage()    {}
func (*AddContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf3c9184062973a1, []int{1}
}

func (m *AddContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContainerResponse.Unmarshal(m, b)
}
func (m *AddContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContainerResponse.Marshal(b, m, deterministic)
}
func (m *AddContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContainerResponse.Merge(m, src)
}
func (m *AddContainerResponse) XXX_Size() int {
	return xxx_messageInfo_AddContainerResponse.Size(m)
}
func (m *AddContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddContainerResponse proto.InternalMessageInfo

func (m *AddContainerResponse) GetDebug() string {
	if m != nil {
		return m.Debug
	}
	return ""
}

type RemoveContainerResponse struct {
	Debug                string   `protobuf:"bytes,1,opt,name=debug,proto3" json:"debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveContainerResponse) Reset()         { *m = RemoveContainerResponse{} }
func (m *RemoveContainerResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveContainerResponse) ProtoMessage()    {}
func (*RemoveContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf3c9184062973a1, []int{2}
}

func (m *RemoveContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveContainerResponse.Unmarshal(m, b)
}
func (m *RemoveContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveContainerResponse.Marshal(b, m, deterministic)
}
func (m *RemoveContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveContainerResponse.Merge(m, src)
}
func (m *RemoveContainerResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveContainerResponse.Size(m)
}
func (m *RemoveContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveContainerResponse proto.InternalMessageInfo

func (m *RemoveContainerResponse) GetDebug() string {
	if m != nil {
		return m.Debug
	}
	return ""
}

type TracerID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TracerID) Reset()         { *m = TracerID{} }
func (m *TracerID) String() string { return proto.CompactTextString(m) }
func (*TracerID) ProtoMessage()    {}
func (*TracerID) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf3c9184062973a1, []int{3}
}

func (m *TracerID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TracerID.Unmarshal(m, b)
}
func (m *TracerID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TracerID.Marshal(b, m, deterministic)
}
func (m *TracerID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TracerID.Merge(m, src)
}
func (m *TracerID) XXX_Size() int {
	return xxx_messageInfo_TracerID.Size(m)
}
func (m *TracerID) XXX_DiscardUnknown() {
	xxx_messageInfo_TracerID.DiscardUnknown(m)
}

var xxx_messageInfo_TracerID proto.InternalMessageInfo

func (m *TracerID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type StreamData struct {
	Line                 string   `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamData) Reset()         { *m = StreamData{} }
func (m *StreamData) String() string { return proto.CompactTextString(m) }
func (*StreamData) ProtoMessage()    {}
func (*StreamData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf3c9184062973a1, []int{4}
}

func (m *StreamData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamData.Unmarshal(m, b)
}
func (m *StreamData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamData.Marshal(b, m, deterministic)
}
func (m *StreamData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamData.Merge(m, src)
}
func (m *StreamData) XXX_Size() int {
	return xxx_messageInfo_StreamData.Size(m)
}
func (m *StreamData) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamData.DiscardUnknown(m)
}

var xxx_messageInfo_StreamData proto.InternalMessageInfo

func (m *StreamData) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

type OwnerReference struct {
	Apiversion           string   `protobuf:"bytes,1,opt,name=apiversion,proto3" json:"apiversion,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Uid                  string   `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OwnerReference) Reset()         { *m = OwnerReference{} }
func (m *OwnerReference) String() string { return proto.CompactTextString(m) }
func (*OwnerReference) ProtoMessage()    {}
func (*OwnerReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf3c9184062973a1, []int{5}
}

func (m *OwnerReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerReference.Unmarshal(m, b)
}
func (m *OwnerReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerReference.Marshal(b, m, deterministic)
}
func (m *OwnerReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerReference.Merge(m, src)
}
func (m *OwnerReference) XXX_Size() int {
	return xxx_messageInfo_OwnerReference.Size(m)
}
func (m *OwnerReference) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerReference.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerReference proto.InternalMessageInfo

func (m *OwnerReference) GetApiversion() string {
	if m != nil {
		return m.Apiversion
	}
	return ""
}

func (m *OwnerReference) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *OwnerReference) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OwnerReference) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type ContainerDefinition struct {
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid       uint32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	OciConfig string `protobuf:"bytes,3,opt,name=oci_config,json=ociConfig,proto3" json:"oci_config,omitempty"`
	// NRI and OCI hooks don't give the OCI config but give pod details
	Namespace            string   `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Podname              string   `protobuf:"bytes,5,opt,name=podname,proto3" json:"podname,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Labels               []*Label `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty"`
	VethPeerName         string   `protobuf:"bytes,8,opt,name=veth_peer_name,json=vethPeerName,proto3" json:"veth_peer_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerDefinition) Reset()         { *m = ContainerDefinition{} }
func (m *ContainerDefinition) String() string { return proto.CompactTextString(m) }
func (*ContainerDefinition) ProtoMessage()    {}
func (*ContainerDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf3c9184062973a1, []int{6}
}

func (m *ContainerDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerDefinition.Unmarshal(m, b)
}
func (m *ContainerDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerDefinition.Marshal(b, m, deterministic)
}
func (m *ContainerDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerDefinition.Merge(m, src)
}
func (m *ContainerDefinition) XXX_Size() int {
	return xxx_messageInfo_ContainerDefinition.Size(m)
}
func (m *ContainerDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerDefinition proto.InternalMessageInfo

func (m *ContainerDefinition) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ContainerDefinition) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *ContainerDefinition) GetOciConfig() string {
	if m != nil {
		return m.OciConfig
	}
	return ""
}

func (m *ContainerDefinition) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ContainerDefinition) GetPodname() string {
	if m != nil {
		return m.Podname
	}
	return ""
}

func (m *ContainerDefinition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContainerDefinition) GetLabels() []*Label {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ContainerDefinition) GetVethPeerName() string {
	if m != nil {
		return m.VethPeerName
	}
	return ""
}

type DumpStateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpStateRequest) Reset()         { *m = DumpStateRequest{} }
func (m *DumpStateRequest) String() string { return proto.CompactTextString(m) }
func (*DumpStateRequest) ProtoMessage()    {}
func (*DumpStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf3c9184062973a1, []int{7}
}

func (m *DumpStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpStateRequest.Unmarshal(m, b)
}
func (m *DumpStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpStateRequest.Marshal(b, m, deterministic)
}
func (m *DumpStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpStateRequest.Merge(m, src)
}
func (m *DumpStateRequest) XXX_Size() int {
	return xxx_messageInfo_DumpStateRequest.Size(m)
}
func (m *DumpStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DumpStateRequest proto.InternalMessageInfo

type Dump struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dump) Reset()         { *m = Dump{} }
func (m *Dump) String() string { return proto.CompactTextString(m) }
func (*Dump) ProtoMessage()    {}
func (*Dump) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf3c9184062973a1, []int{8}
}

func (m *Dump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dump.Unmarshal(m, b)
}
func (m *Dump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dump.Marshal(b, m, deterministic)
}
func (m *Dump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dump.Merge(m, src)
}
func (m *Dump) XXX_Size() int {
	return xxx_messageInfo_Dump.Size(m)
}
func (m *Dump) XXX_DiscardUnknown() {
	xxx_messageInfo_Dump.DiscardUnknown(m)
}

var xxx_messageInfo_Dump proto.InternalMessageInfo

func (m *Dump) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func init() {
	proto.RegisterType((*Label)(nil), "gadgettracermanager.Label")
	proto.RegisterType((*AddContainerResponse)(nil), "gadgettracermanager.AddContainerResponse")
	proto.RegisterType((*RemoveContainerResponse)(nil), "gadgettracermanager.RemoveContainerResponse")
	proto.RegisterType((*TracerID)(nil), "gadgettracermanager.TracerID")
	proto.RegisterType((*StreamData)(nil), "gadgettracermanager.StreamData")
	proto.RegisterType((*OwnerReference)(nil), "gadgettracermanager.OwnerReference")
	proto.RegisterType((*ContainerDefinition)(nil), "gadgettracermanager.ContainerDefinition")
	proto.RegisterType((*DumpStateRequest)(nil), "gadgettracermanager.DumpStateRequest")
	proto.RegisterType((*Dump)(nil), "gadgettracermanager.Dump")
}

func init() {
	proto.RegisterFile("api/gadgettracermanager.proto", fileDescriptor_bf3c9184062973a1)
}

var fileDescriptor_bf3c9184062973a1 = []byte{
	// 528 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0x6d, 0xd7, 0x3f, 0x5b, 0xef, 0x6f, 0xeb, 0x6f, 0x72, 0x27, 0x11, 0xaa, 0x15, 0x2a, 0x0b,
	0xa4, 0x22, 0x8d, 0x06, 0x95, 0x47, 0xc4, 0x03, 0xac, 0x12, 0x42, 0x02, 0x86, 0x52, 0x9e, 0x78,
	0xa9, 0xdc, 0xe4, 0x36, 0x33, 0x69, 0xec, 0xe0, 0x38, 0x41, 0x7c, 0x0a, 0xbe, 0x30, 0x0f, 0xc8,
	0x4e, 0xda, 0x55, 0x95, 0x27, 0xc1, 0xdb, 0xf5, 0xb9, 0x7f, 0xce, 0x8d, 0xcf, 0x89, 0x61, 0xc4,
	0x32, 0xee, 0xc7, 0x2c, 0x8a, 0x51, 0x6b, 0xc5, 0x42, 0x54, 0x29, 0x13, 0x2c, 0x46, 0x35, 0xcd,
	0x94, 0xd4, 0x92, 0x0c, 0x1c, 0x29, 0xea, 0x43, 0xe7, 0x03, 0x5b, 0xe1, 0x86, 0x9c, 0x43, 0x2b,
	0xc1, 0x9f, 0x5e, 0x73, 0xdc, 0x9c, 0xf4, 0x02, 0x13, 0x92, 0x0b, 0xe8, 0x94, 0x6c, 0x53, 0xa0,
	0x77, 0x64, 0xb1, 0xea, 0x40, 0xaf, 0xe0, 0xe2, 0x4d, 0x14, 0x5d, 0x4b, 0xa1, 0x19, 0x17, 0xa8,
	0x02, 0xcc, 0x33, 0x29, 0x72, 0x34, 0xd5, 0x11, 0xae, 0x8a, 0xb8, 0x9e, 0x50, 0x1d, 0xa8, 0x0f,
	0x0f, 0x02, 0x4c, 0x65, 0x89, 0x7f, 0xdb, 0x30, 0x84, 0x93, 0x2f, 0x76, 0xc1, 0xf7, 0x73, 0xd2,
	0x87, 0x23, 0x1e, 0xd5, 0xe9, 0x23, 0x1e, 0xd1, 0x31, 0xc0, 0x42, 0x2b, 0x64, 0xe9, 0x9c, 0x69,
	0x46, 0x08, 0xb4, 0x37, 0x5c, 0x60, 0x9d, 0xb7, 0x31, 0xfd, 0x06, 0xfd, 0x9b, 0x1f, 0x96, 0x64,
	0x8d, 0x0a, 0x45, 0x88, 0xe4, 0x11, 0x00, 0xcb, 0x78, 0x89, 0x2a, 0xe7, 0x52, 0xd4, 0xb5, 0x7b,
	0x88, 0x99, 0x92, 0x70, 0x11, 0xd5, 0xdf, 0x68, 0x63, 0x83, 0x09, 0x96, 0xa2, 0xd7, 0xaa, 0x30,
	0x13, 0x9b, 0xeb, 0x29, 0x78, 0xe4, 0xb5, 0xab, 0xeb, 0x29, 0x78, 0x44, 0x7f, 0x37, 0x61, 0xb0,
	0xfb, 0xaa, 0x39, 0xae, 0xb9, 0xe0, 0xda, 0x4c, 0x3c, 0xd8, 0xda, 0x74, 0x66, 0xbc, 0x22, 0x38,
	0x0b, 0x4c, 0x48, 0x46, 0x00, 0x32, 0xe4, 0xcb, 0x50, 0x8a, 0x35, 0x8f, 0x6b, 0x96, 0x9e, 0x0c,
	0xf9, 0xb5, 0x05, 0xc8, 0x25, 0xf4, 0x0c, 0x65, 0x9e, 0xb1, 0x10, 0x6b, 0xc2, 0x3b, 0x80, 0x78,
	0x70, 0x9c, 0xc9, 0xc8, 0xee, 0xd7, 0xb1, 0xb9, 0xed, 0x71, 0xb7, 0x76, 0x77, 0x6f, 0xed, 0x19,
	0x74, 0x37, 0x46, 0xde, 0xdc, 0x3b, 0x1e, 0xb7, 0x26, 0xff, 0xcd, 0x86, 0x53, 0x97, 0x3f, 0xac,
	0x03, 0x82, 0xba, 0x92, 0x3c, 0x81, 0x7e, 0x89, 0xfa, 0x76, 0x99, 0x21, 0xaa, 0xa5, 0x9d, 0x78,
	0x62, 0x27, 0x9e, 0x1a, 0xf4, 0x33, 0xa2, 0xfa, 0xc4, 0x52, 0xa4, 0x04, 0xce, 0xe7, 0x45, 0x9a,
	0x2d, 0x34, 0xd3, 0x18, 0xe0, 0xf7, 0x02, 0x73, 0x4d, 0x2f, 0xa1, 0x6d, 0x30, 0x23, 0x6d, 0x6e,
	0xf0, 0xad, 0xb4, 0xf6, 0x30, 0xfb, 0xd5, 0x82, 0xc1, 0x3b, 0xcb, 0x5e, 0x29, 0xfc, 0xb1, 0x62,
	0x27, 0x0b, 0x38, 0x0b, 0x30, 0x44, 0x5e, 0x62, 0xa5, 0x2e, 0x19, 0x39, 0x97, 0xdc, 0xda, 0x62,
	0xf8, 0xd8, 0x99, 0xbe, 0x73, 0x06, 0x6d, 0xbc, 0x68, 0x12, 0x84, 0xd3, 0x7d, 0x9b, 0x92, 0x89,
	0xb3, 0xc9, 0xa1, 0xdf, 0xf0, 0x99, 0xb3, 0xd2, 0xe5, 0x79, 0xda, 0x20, 0x09, 0xfc, 0x7f, 0xe0,
	0xef, 0x7f, 0x60, 0xba, 0x72, 0x56, 0xde, 0xf3, 0xbf, 0xd0, 0x06, 0xb9, 0x81, 0xde, 0xee, 0xca,
	0xc9, 0x53, 0x67, 0xf3, 0xa1, 0x24, 0xc3, 0x87, 0xf7, 0x96, 0xd1, 0xc6, 0xdb, 0xd7, 0x5f, 0x5f,
	0xc5, 0x5c, 0xdf, 0x16, 0xab, 0x69, 0x28, 0x53, 0x3f, 0xe1, 0xa2, 0x94, 0x9b, 0xc4, 0xe7, 0x22,
	0xcf, 0x30, 0xd1, 0x52, 0x3d, 0xaf, 0x5a, 0xfd, 0x2c, 0x89, 0x5d, 0xcf, 0xca, 0xaa, 0x6b, 0xdf,
	0x95, 0x97, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x17, 0x76, 0xe2, 0x78, 0x04, 0x00, 0x00,
}
